# https://hub.docker.com/_/mysql
version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080